php/models/Notification.php
<?php

declare(strict_types=1);

namespace app\models;

use Yii;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "notification".
 *
 * @property integer $id
 * @property string $text
 * @property string $creation_date
 * @property string $extra
 * @property integer $task_id
 * @property string $command
 * @property integer $type
 * @property integer $level
 * @property integer $taken_by_user_id
 * @property string $short_info
 *
 * @property Task $task
 */
class Notification extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName() : string
    {
        return 'notification';
    }

    /**
     * @inheritdoc
     */
    public function rules() : array
    {
        return [
            [['creation_date'], 'safe'],
            [['extra'], 'string'],
            [['task_id'], 'required'],
            [['task_id', 'type', 'level', 'taken_by_user_id'], 'integer'],
            [['short_info'], 'string', 'max' => 255],
            [['text'], 'string', 'max' => 4000],
            [['command'], 'string', 'max' => 512],
            [['task_id'], 'exist', 'skipOnError' => true, 'targetClass' => Task::className(), 'targetAttribute' => ['task_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() : array
    {
        return [
            'id' => 'ID',
            'text' => 'текст уведомления',
            'creation_date' => 'Creation Date',
            'extra' => 'дополнительное поле для помещения кастомных данных, которые возможно понадобятся позже',
            'task_id' => 'связь с задачей',
            'command' => 'Оригинальная команда, которая привела к выбросу уведомления',
            'type' => 'тип уведомления (бага, RCE и прочее)',
            'level' => 'уровень уведомления (некритичный, критический и прочее)',
            'taken_by_user_id' => 'Взят пользователем',
            'short_info' => 'Краткая информация',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTask() : ActiveQuery
    {
        return $this->hasOne(Task::className(), ['id' => 'task_id']);
    }
    
    public function getErrorsAsString() : string
    {
        $string = '';
        $errors = $this->getErrors();
        foreach ($errors as $attributeName => &$attributeErrors) {
            $string .= "\nAttribute - '$attributeName':\n" . implode("\n", $attributeErrors);
        }
        return $string;
    }
    
    /**
     * Создано ли уведомление задачей администратора
     * @return bool
     */
    public function isCreatedByAdmin() : bool
    {
        return intval(Task::find()
            ->select(['user.id'])
            ->leftJoin('user', 'user.id = task.user_id')
            ->where(['task.id' => $this->task_id])->count()) === 1;       
    }
}

php/controllers/NotificationController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use Yii;
use app\models\Notification;
use app\models\NotificationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\auth\User;
use yii\filters\AccessControl;

/**
 * NotificationController implements the CRUD actions for Notification model.
 */
class NotificationController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','view', 'take', 'free', 'general'],
                'rules' => [
                    [
                        'actions' => ['index','view', 'take', 'free', 'general'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Notification models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->searchForCurrentUserOnly(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Notification model.
     * @param integer $id
     * @return mixed
     */
    public function actionView(int $id) : string
    {
        $model = $this->findModel($id);
        $task = $model->getTask()->one();       
        $userId = User::getCurrentUserId();
        
        if ($model->taken_by_user_id !== $userId && $task->user_id !== $userId)
        {
            throw new \Exception('Can not get access to record');
        }
        
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Notification model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Notification the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Notification
    {
        if (($model = Notification::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * 
     * @param int $id
     * @return string
     * @throws \LogicException
     */
    public function actionTake(int $id) 
    {
        try
        {
            $model = $this->findModel($id);
            $user = User::getCurrentUser();
            
            //Если уже взято - редиректим
            if ($model->taken_by_user_id === $user->id)
            {
                return $this->redirect(['view', 'id' => $id]);
            }
            
            if ($user->isAdmin())
            {
                throw new \LogicException('User is admin');
            }
            if (!$model->isCreatedByAdmin())
            {
                throw new \LogicException('Motification is not created by admin task');
            }

            $model->taken_by_user_id = $user->id;
            if (!$model->validate())
            {
                throw new \LogicException('Model->validate() error');
            } 
            $model->save();
            return $this->redirect(['view', 'id' => $id]);
        } catch (\Exception $ex) {
            \Yii::error(__METHOD__.": ".$ex->getMessage());
            return $this->redirect(['general']);
        }          
    }
    
    /**
     * 
     * @param integer $id
     * @return type
     */
    public function actionFree(int $id)
    {
        try
        {
            $user = User::getCurrentUser();
            if ($user->isAdmin())
            {
                throw new \LogicException('User is admin');
            }
            
            $model = $this->findModel($id);
            if ($model->taken_by_user_id !== User::getCurrentUserId())
            {
                return $this->redirect(['index']);
            }
            
            $model->taken_by_user_id = null;
            $model->save();
                    
        } catch (\Exception $ex) {
            \Yii::error(__METHOD__.": ".$ex->getMessage());
        }
        return $this->redirect(['general']);
    }
    
    /**
     * Страница уведомлений, которые были созданы от задач администраторов
     * @return string
     */
    public function actionGeneral() : string
    {
        $searchModel = new NotificationSearch();
        $dataProvider = $searchModel->searchCreatedByAdmin(Yii::$app->request->queryParams);

        return $this->render('general', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}

php/controllers/TaskController.php
<?php

declare(strict_types=1);

namespace app\controllers;

use Yii;
use app\models\Task;
use app\models\TaskSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\models\auth\User;
use yii\filters\AccessControl;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends BaseController
{
    /**
     *
     * @var string 
     */
    protected static $nonAdminMesage = 'текущий пользователь не является администратором';

    /**
     * @inheritdoc
     */
    public function behaviors() : array
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'approve', 'push'],
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'approve', 'push'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() : string
    {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView(int $id) : string
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
            'domains' => $model->readDomains(),
            'domainsCount' => 0,
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $response = new Response();
            $response = $this->render('create', [
                'model' => $model,
                //'domains' => $model->readDomains(),
            ]);
            return $response;
        }
    }
    
    /**
     * 
     * @param int $id
     */
    public function actionApprove(int $id)
    {
        if (!User::currentUserIsAdmin())
        {
            \Yii::error(__METHOD__.": ".self::$nonAdminMesage);
            return $this->redirect(['view', 'id' => $model->id]);
        } 
        
        return $this->redirect(['view', 'id' => $id]);
    }
    
    /**
     * 
     * @param integer $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionPush(int $id) : string
    {
        $model = $this->findModel($id);
        if (!User::currentUserIsAdmin())
        {
            \Yii::error(__METHOD__.": ".self::$nonAdminMesage);
            return $this->redirect(['view', 'id' => $model->id]);
        }
        
        if ($model->status !== Task::STATUS_APPROVED)
        {
            throw new \Exception('Task must be in "approved" status');
        }
        if (!$model)
        {
            throw new NotFoundHttpException('Not found task with id '.$id);
        }
        
        $domainsCount = $model->pushToQueue('task');
        return $this->render('view', [
            'model' => $model,
            'domains' => $model->readDomains(),
            'domainsCount' => $domainsCount,
        ]);      
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel(int $id) : Task
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php/views/notification/general.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\auth\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NotificationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Notifications';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Notification', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'short_info',
            'creation_date',
            'type',
            'level',
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'take' => function ($url, $model, $key) {
                        if ($model->taken_by_user_id === User::getCurrentUserId())
                        {
                            return '';
                        }
                        
                        $data = [
                            'notification/take', 
                            'id' => $model->id,
                            ];
                        $icon = 'fa-file-import';
                        return Html::a ( '<span class="fa '.$icon.'" aria-hidden="true"></span> ', $data);
                    },
                ],
                'template' => '{take} {free}', 
            ],
        ],
    ]); ?>
</div>

php/views/notification/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use app\models\auth\User;

/* @var $this yii\web\View */
/* @var $searchModel app\models\NotificationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Notifications';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Notification', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'short_info',
            'creation_date',
            'type',
            'level',
            [
                'attribute' => 'task_id',
                'format' => 'raw',
                'value' => function ($model) {
                    $task = $model->getTask()->one();
                    return Html::a(Html::encode($task->name), 
                    Url::to(['task/view', 'id' => $task->id]));
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'free' => function ($url, $model, $key) {
                        if ($model->taken_by_user_id !== User::getCurrentUserId())
                        {
                            return '';
                        }                       
                        $data = [
                            'notification/free', 
                            'id' => $model->id,
                            ];
                        $icon = 'fa-file-export';
                        return Html::a ( '<span class="fa '.$icon.'" aria-hidden="true"></span> ', $data);
                    },
                ],
                'template' => '{view} {free}'
            ],
            
        ],
    ]); ?>
</div>

php/views/notification/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\models\auth\User;

/* @var $this yii\web\View */
/* @var $model app\models\Notification */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Notifications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="notification-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php
            if ($model->taken_by_user_id === User::getCurrentUserId())
            {
                echo Html::a(
                        'Free', [
                        'free', 'id' => $model->id], 
                        ['class' => 'btn btn-primary']
                    );
            }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'text',
            'creation_date',
            'extra:ntext',
            'command',
            'type',
            'level',
        ],
    ]) ?>

</div>